---
title: Turtle snowflakes
hero_image: images/banner.png
description: Write code to draw snowflakes with Python Turtle
original_url: https://raspberrypi.org/learning/turtle-snowflakes
theme: navy
duration: 1
listed: false
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: art
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Step 1
- title: Step 2
- title: Step 3
  completion:
  - engaged
- title: Step 4
- title: Step 5
- title: Step 6
- title: Step 7
- title: Step 8
- title: Step 9
- title: Step 10
- title: Step 11
- title: Step 12
- title: Step 13
  completion:
  - internal
- title: Step 14
  completion:
  - external
